name: Deploy to TrueHost

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Deploy via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.shamsub.com.ng          # ✅ TrueHost FTP server
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/                  # ✅ Build output folder
          server-dir: /public_html/           # ✅ Remote folder
          protocol: ftp
          port: 21
          timeout: 120000                     # ✅ 120 seconds (2 mins)

          
