name: Deploy to TrueHost
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out code (includes your pre-built /build folder)
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Deploy via FTP
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ftp.yourdomain.com      # TrueHost FTP server
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./dist/             # Deploy this folder
          server-dir: /public_html/       # TrueHost target
